### PR TITLE
fix: Use PACKAGE_PREFIX_DIR to ensure relocatable CMake install for conan

### PR DESCRIPTION
**Pull request by Pro**
Using CMAKE_INSTALL_PREFIX causes build issues when you relocate the installed CMake package, i.e., as it is done in conan.

CMAKE_INSTALL_PREFIX should not be used in the cmake.in files directly. The `@PACKAGE_INIT@` macro initializes `PACKAGE_PREFIX_DIR` correspondingly.

See also:
https://github.com/ignitionrobotics/ign-cmake/pull/129
https://github.com/osrf/sdformat/pull/419
https://github.com/osrf/gazebo/issues/2782

cc @stefanbuettner

### CODE REVIEW

**Review by caguero — APPROVED** [review]
@Pro, thanks for the contribution! I tried out and it seems to work fine. Approving!

**Comment by traversaro** [comment]
Note that the change in the `.pc` file here could break Debian packaging for the reasons described in https://github.com/dartsim/dart/pull/1527#discussion_r525493125 . fyi @j-rivero

**Comment by caguero** [comment]
Thanks @traversaro! @j-rivero , do you foresee any issues?

**Comment by scpeters** [comment]
> Note that the change in the `.pc` file here could break Debian packaging for the reasons described in [dartsim/dart#1527 (comment)](https://github.com/dartsim/dart/pull/1527#discussion_r525493125) . fyi @j-rivero

I made that comment on dartsim, and yes I think it will break our `.pc` files on Ubuntu, since the relative path is not correct when installed to an architecture-dependent subfolder like `/usr/lib/x86_64-linux-gnu/pkgconfig`

**Comment by jslee02** [comment]
@scpeters Consider using the technique used in https://github.com/dartsim/dart/pull/1529. It should work even for the case you described.

**Pull request merged**
