### PR TITLE
Add Windows installation

### PR DESCRIPTION
**Pull request by mabelzhang**
Redo of #32............ Is third try the charm?

Copy of description:

Partially addresses ignitionrobotics/docs#117

I haven't added a tutorial page to address this other issue ignitionrobotics/docs#14 (comment) , since ign-tools is "tricky"? Do we want a tutorial page for it?

### CODE REVIEW

**Comment by mabelzhang** [comment]
Now I know how to read the colorful labels on the right.

**Review by JShep1 — COMMENTED** [review]
Looks good, should we perhaps have a note indicating that the `ign` command lines are currently building, but not functional for Windows?

**Comment by mabelzhang** [comment]
Do you think it'll be fixed in the short term (since you're looking into it), or do you expect it to be there for the long term? Maybe we don't need to add it if you have to remember to remove it in a week or two.

**Comment by JShep1** [comment]
> Do you think it'll be fixed in the short term (since you're looking into it), or do you expect it to be there for the long term? Maybe we don't need to add it if you have to remember to remove it in a week or two.

I just took a quick look, I built `ign-tools` from source on Windows and it generates a `ign` ruby script which can be run with `ruby ign`, although installing or sourcing the workspace built with `colcon` does not allow this ruby command to find the necessary `yaml` files.

This is likely due to the searched directory being `C:/Program Files (x86)/ignition-tools/share/ignition/`, I manually modified the file to search the actual install directory `C:/Users/asus/test-ws/install/share/ignition` and the commands for the built packages were found.  I think this _should_ be a quick fix....

**Comment by JShep1** [comment]
The problem to solve after the above mentioned one is to have the `ign` command line utility usable after the environment is sourced with `call install\setup.bat`, which I haven't spent time on yet so I'm unsure why exactly this is occurring.

**Comment by mabelzhang** [comment]
Thanks for looking into it! I added a note in c197106 for now.
Feel free to add a troubleshoot section to the guide you linked. Sounds good.

Did you have to set `CMAKE_INSTALL_PREFIX` to something specific? I only compiled SOME libraries from source, so I had `CMAKE_INSTALL_PREFIX` set to the directory where the previous library was compiled from source. Since most of my libraries were installed from `conda-forge` (for the sake of writing the per-library tutorials), it wasn't uniform across all the libraries. Maybe you have a better idea from a full source install.

**Comment by JShep1** [comment]
Yes, I had to specify where the directory where the previous library was compiled for `CMAKE_INSTALL_PREFIX`, `colcon` makes this a lot more simplified.

Additionally, the `ign` command line utility works only so far as locating the commands that each package provides, at this point, attempting to invoke any of the command line utilities results in a ruby crash having to do with (I think) the loading of the ignition shared object file, I believe @chapulina mentioned this might have to do with the ruby versions that the ruby scripts are built with?

**Review by JShep1 — APPROVED** [review]

**Pull request merged**
